main: me.armar.plugins.autorank.Autorank
name: Autorank
softdepend: [Vault, Essentials, GroupManager, Stats, WorldEdit, WorldGuard, Factions, mcMMO, RoyalCommands, OnTime, Privileges, bPermissions, PermissionsEx, PermissionsBukkit, DroxPerms, UltimateCore]
url: http://dev.bukkit.org/bukkit-plugins/autorank/
version: ${project.version}
authors: [Idrrp, Armarr, Staartvin]
description: Reward players based on their stats.
commands:
    autorank:
        description: Master command of AutoRank
        usage: Autorank is disabled. Check your server.log!
        aliases: [ar]
permissions:
    autorank.check:
        description: Allows checking the recommended rank.
        default: true
    autorank.checkothers:
        description: Allows checking the recommended rank of other players.
        default: op
    autorank.leaderboard:
        description: Allows looking at the leaderboards.
        default: true
    autorank.exclude:
        description: Excludes groups or users from the autorank checks.
        default: false
    autorank.timeexclude:
        description: Excludes groups or users from the playtime updates.
        default: false
    autorank.set.self:
        description: Allows changing own playtime.
        default: op
    autorank.set.other:
        description: Allows changing others playtime.
        default: op
    autorank.add:
        description: Allows adding to playtimes.
        default: op
    autorank.remove:
        description: Allows substracting from playtimes.
        default: op
    autorank.debug:
        description: Displays debugging information.
        default: op
    autorank.reload:
        description: Allows reloading the config.
        default: op
    autorank.import:
        description: Allows importing old data.
        default: op
    autorank.archive:
        description: Allows a player to archive old data.
        default: op
    autorank.noticeonupdate:
        description: When a new update is available, Autorank will tell all players with this permission that a new version is available.
        default: op
    autorank.sync:
        description: Allows a player to do /ar sync
        default: op
    autorank.syncstats:
        description: Allows a player to do /ar syncstats
        default: op    
    autorank.complete:
        description: Allows a player to do /ar complete
        default: op    
    autorank.forcecheck:
        description: Allows a player to forcecheck another player
        default: op
    autorank.warning.notice:
        description: Allows a player to see warnings when problems occur with Autorank.
        default: op
    autorank.convert.playerdata:
        description: Allows a player to convert the playerdata to UUID format.
        default: op
    autorank.convert.data:
        description: Allows a player to convert the data.yml to UUID format.
        default: op
    autorank.help:
        description: Allows a player to view a list of commands
        default: true
    autorank.leaderboard.exempt:
        description: Exempts a player from the leaderboard.
        default: false    
